### ISSUE TITLE
Chaincode code management  with Tekton CI

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#92]
Subtasks
- [x] integrate Tekton CI into k8s with [installer] (https://github.com/bestchains/installer/issues) bestchains/installer#13
- [x] define a new CRD  `ChaincodeBuild` #156
- [x] develop operator controller for CRD  `ChaincodeBuild` #156
